export const ErrorCodes = {
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  REDIS_ERROR: 'REDIS_ERROR',
  RAZORPAY_ERROR: 'RAZORPAY_ERROR',
  WEBHOOK_SIGNATURE_ERROR: 'WEBHOOK_SIGNATURE_ERROR',
  WEBHOOK_DUPLICATE: 'WEBHOOK_DUPLICATE',
  AI_ERROR: 'AI_ERROR',
  SCORING_ERROR: 'SCORING_ERROR',
  RECONCILIATION_ERROR: 'RECONCILIATION_ERROR',
  RATE_LIMIT_ERROR: 'RATE_LIMIT_ERROR',
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCode = keyof typeof ErrorCodes;
