/* eslint-disable @typescript-eslint/no-explicit-any */
import { generateObject } from "ai";
import { z } from "zod";
import { AI_MODELS } from "../../ai/config";
import { DetectedAnomaly } from "./analyzer";

export const LeakageAIOutputSchema = z.object({
  whatHappened: z.string().describe("Factual summary of the detected anomaly."),
  whyItMatters: z.string().describe("Revenue and business impact."),
  observedPattern: z.string().describe("The specific pattern observed in the data without assuming external factors."),
  inferredCause: z.string().describe("Likely cause based strictly on the provided evidence. State clearly if the cause cannot be determined."),
  causeConfidence: z.number().min(0).max(1).describe("Confidence in the inferred cause."),
  investigationStrategy: z.string().describe("Recommended strategy for a human to investigate or recover this leakage.")
});

export type LeakageAIOutput = z.infer<typeof LeakageAIOutputSchema>;

export async function runLeakageDetectiveAgent(
  anomaly: DetectedAnomaly,
  merchantContext: any
): Promise<LeakageAIOutput> {
  if (process.env.MOCK_AI === "true") {
    return {
      whatHappened: `Simulated anomaly for ${anomaly.leakageCategory}`,
      whyItMatters: "High impact",
      observedPattern: "Spike detected",
      inferredCause: anomaly.leakageCategory === "DISPUTE_LOSS" ? "Cause cannot be determined from available data" : "Network error",
      causeConfidence: 0.5,
      investigationStrategy: "Review logs"
    };
  }

  const model = AI_MODELS.leakageDetective;

  const prompt = `
You are the AI Revenue Leakage Detective for RecoverAI.
Your goal is to interpret deterministic anomaly evidence and provide clear, factual analysis.

WARNING: You must NEVER invent financial evidence, amounts, counts, percentages, baselines, or affected customers.
You must NEVER state unsupported causes (e.g., "UPI downtime") as facts if the evidence does not establish it.
If the evidence does not clearly point to a cause, explicitly state that the cause cannot be determined.

Merchant Context:
${JSON.stringify(merchantContext, null, 2)}

Detected Anomaly Category: ${anomaly.leakageCategory}

Factual Evidence (Generated by Deterministic Analyzer):
${JSON.stringify(anomaly.evidence, null, 2)}

Provide a structured analysis matching the requested JSON schema.
Distinguish between amount at risk (e.g., failed payments that might be retried) and amount actually lost (e.g., dispute loss where recovery is 0).
`;

  const result = await generateObject({
    model,
    schema: LeakageAIOutputSchema,
    prompt,
    temperature: 0.1,
  });

  return result.object;
}
